# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cf4c18476b4cf24b1389e0f68b45516f6ca518aee5d3901baae0c2be5d376117820a15d761d9403b6be18ada0694e99f67716da5cc734744a4804db8a7131d6

test:
  secret_key_base: 789389841d23fc66a7f0e7bc348b34608073a3f5dcc24d99fae5b156832068ddf1a2024b60a5fd83ad727dcd79c2e8ab67fcff894f936fc4dfbcb187fc090954

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
